// Generated by dojo-bindgen on Sat, 7 Dec 2024 22:22:09 +0000. Do not modify this file manually.
using System;
using Dojo;
using Dojo.Starknet;
using System.Reflection;
using System.Linq;
using System.Collections.Generic;
using Enum = Dojo.Starknet.Enum;
using BigInteger = System.Numerics.BigInteger;

// Type definition for `dojo_starter::models::Direction` enum
public abstract record Direction() : Enum {
    public record None() : Direction;
    public record Left() : Direction;
    public record Right() : Direction;
    public record Up() : Direction;
    public record Down() : Direction;
}


// Model definition for `dojo_starter::models::Moves` model
public class dojo_starter_Moves : ModelInstance {
    [ModelField("player")]
        public FieldElement player;

        [ModelField("remaining")]
        public byte remaining;

        [ModelField("last_direction")]
        public Direction last_direction;

        [ModelField("can_move")]
        public bool can_move;

    // Start is called before the first frame update
    void Start() {
    }

    // Update is called once per frame
    void Update() {
    }
}

        